### ISSUE TITLE
Rules of the annotations for long curve texts.

### ISSUE THREAD

**Issue by zxDeepDiver** [Yuliang-Liu/Curve-Text-Detector#10]
Hi, 

The CWT dataset is great. But I have been puzzled for the annotations of the long curve texts.
Sometimes, each long curve text line has a single annotation, while sometimes the annotation is cut from the middle.
![image](https://user-images.githubusercontent.com/7352077/39977109-39b7e730-576a-11e8-96c0-d16435046a94.png)
![image](https://user-images.githubusercontent.com/7352077/39977130-4b420b3e-576a-11e8-8689-f044b7f47011.png)

So could you please explain for me the guidelines of the annotation rules? 
Thank you so much.

**Comment by Yuliang-Liu** [comment]
Hi there,


There is not specific rule to label such long text. Most of the text is subjectively annotated based on the text reading direction. I know this is not perfect, and we are trying to figure out an objective way to label such text.

BTW: The sequence of the annotated points of each bounding box strictly follows the text reading direction.


Thanks for your attention.


Regards.

Yuliang Liu
