### ISSUE TITLE
QObject::moveToThread: Current thread (0x55c07be39a60) is not the object's thread (0x55c07c164490). Cannot move to target thread (0x55c07be39a60)

### ISSUE THREAD

**Issue by danmeng90** [Yuliang-Liu/Curve-Text-Detector#11]
Hello, Liu:

I am running your code on Ubuntu16.04, however, when I run python demo.py, the following two lines showed repeatedly:

QObject::moveToThread: Current thread (0x55c07be39a60) is not the object's thread (0x55c07c164490).
Cannot move to target thread (0x55c07be39a60)

Is it a normal phenomenon or there's something wrong with my operation? Thank you for your time.

                                                                                                                                     Dan Meng

**Comment by Yuliang-Liu** [comment]
Hi there:

I have tested the code on several computers, but the error didn't occur.
Could you show more details about the error logs?

**Comment by CharlesJWC** [comment]
I was able to fix this problem by installing new pyqt.

if you are using anaconda, just write down below:

$ conda install pyqt

**Comment by theRealSuperMario** [comment]
> I was able to fix this problem by installing new pyqt.
> 
> if you are using anaconda, just write down below:
> 
> $ conda install pyqt

I can confirm that. A working combination seems to be opencv-python==4.1.0.25 and pyqt 5.9.2

**Comment by WaseemSabir** [comment]
opencv-python==4.1.0.25 is not available for anaconda environment on Ubuntu. the version opencv-python==4.3.0.36 and above pyqt version 5.9.2 works fine! solved the issue for me!

**Comment by schauppi** [comment]
I resolved this error by downgrading from opencv-python 4.5.1.48 to opencv-python 4.3.0.36 with PyQt5 5.15.2 installed.

**Comment by Nurullah1313** [comment]
> I resolved this error by downgrading from opencv-python 4.5.1.48 to opencv-python 4.3.0.36 with PyQt5 5.15.2 installed.
Thanks to you I solved

**Comment by Nurullah1313** [comment]
Thanks to you I solved @schauppi

**Comment by Nurullah1313** [comment]
Thank you very much thanks to @schauppi, I solved it

**Comment by mikechen66** [comment]
> > I was able to fix this problem by installing new pyqt.
> > if you are using anaconda, just write down below:
> > $ conda install pyqt
> 
> I can confirm that. A working combination seems to be opencv-python==4.1.0.25 and pyqt 5.9.2

It does not help me out. It has repeated the same error.

**Comment by YunfeiZHAO** [comment]
make be change cv2.waitKey(0) to cv2.waitKey(1) can solve your problem

**Comment by HosikChae** [comment]
> I resolved this error by downgrading from opencv-python 4.5.1.48 to opencv-python 4.3.0.36 with PyQt5 5.15.2 installed.

`python3.6`, `opencv-python`==4.3.0.36, `pyqt5`==5.15.2 worked for me.
(`opencv-python`==4.3.0.38 and all above didn't work)

**Comment by CharlesNord** [comment]
Python3.8, ubuntu 18.04.1 , 

`pip install opencv-python==4.2.0.32`

solves my problem

**Comment by daigz1224** [comment]
Python 3.8, Ubuntu 18.04, Conda Environment,
I resolved this error by removing `opencv-python` installed by pip, and use `opencv` installed by conda instead.

**Comment by ykn96** [comment]
I am unable to downgrade my opencv, what options do I have ?

```
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32
ERROR: No matching distribution found for opencv-python==4.2.0.32
````
and
```
ERROR: Could not find a version that satisfies the requirement 4.3.0.36
ERROR: No matching distribution found for 4.3.0.36

````

**Comment by itsbvk** [comment]
> I am unable to downgrade my opencv, what options do I have ?
> 
> ```
> ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32
> ERROR: No matching distribution found for opencv-python==4.2.0.32
> ```
> 
> and
> 
> ```
> ERROR: Could not find a version that satisfies the requirement 4.3.0.36
> ERROR: No matching distribution found for 4.3.0.36
> ```

@fatbringer 4.3.0.36 is compatible for only certain python versions. Check your python version against the available builds.. https://pypi.org/project/opencv-python/4.3.0.36/

**Comment by RamaKrishnaMarri** [comment]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QObject::moveToThread: Current thread (0x261a670) is not the object's thread (0x3cd8880).
Cannot move to target thread (0x261a670)

QObject::moveToThread: Current thread (0x261a670) is not the object's thread (0x3cd8880).
Cannot move to target thread (0x261a670)
