### ISSUE TITLE
converter error ubuntu 18

### ISSUE THREAD

**Issue by maideribarra** [Yuliang-Liu/Curve-Text-Detector#12]
Hi I have this error, do you know why could it be?I am testing it in ubuntu 18.
TypeError: No registered converter was able to extract a C++ pointer to type char from this Python object of type str
Traceback (most recent call last):
  File "./tools/test_net.py", line 100, in <module>
    net = caffe.Net(args.prototxt, args.caffemodel, caffe.TEST)
SystemError: NULL result without error in PyObject_Call

**Comment by Yuliang-Liu** [comment]
Hi. I haven't encounter such error,  cuz I only tested the code in ubuntu 14.04 and 16.04 (Maybe you could try in these two versions?).

Best regards,
Yuliang Liu
