### ISSUE TITLE
PyTorch version?

### ISSUE THREAD

**Issue by cbasavaraj** [Yuliang-Liu/Curve-Text-Detector#13]
Hi,
Thanks for the repo, very useful for a project I'm trying to do.
I tried running the demo on my MacBook Pro (no CUDA GPU), and it seems a bit of effort to get Caffe up and running on a Mac. 
In any case, I work mostly on PyTorch. I can try porting your checkpoint and prototxt to PyTorch,   but do you know if anyone has already done this?
Thanks

**Comment by Yuliang-Liu** [comment]
Hi,

I'm not idea who had done this before. Maybe I will try to constrcut a PyTorch version in the future.

Thanks for your attention.

**Comment by rookiecm** [comment]
> Hi,
> 
> I'm not idea who had done this before. Maybe I will try to constrcut a PyTorch version in the future.
> 
> Thanks for your attention.

Hello,
Have u completed the code of Pytorch version? and when will u publish it?
Thanks

**Comment by Yuliang-Liu** [comment]
I will release a better curved text detector based on Pytorch version soon if everythin goes well.

Thanks
