### ISSUE TITLE
ImportError: No module named decorator

### ISSUE THREAD

**Issue by JohnWnx** [Yuliang-Liu/Curve-Text-Detector#14]
Hi, despite having installed decorator:
![image](https://user-images.githubusercontent.com/40804580/43907225-91bb18e2-9c27-11e8-88e7-0db4fa7e1d79.png)

I'm still getting the error below when I try to train/run:
![image](https://user-images.githubusercontent.com/40804580/43907293-b44cad6c-9c27-11e8-9c23-1aab9866ae4f.png)
![image](https://user-images.githubusercontent.com/40804580/43907325-c2c467ae-9c27-11e8-807c-5e5eeccee674.png)

Can anyone advise me on this?

Thanks!

**Comment by Yuliang-Liu** [comment]
Hi there,
You can refer to the links below to solve your problem:
https://github.com/udacity/sdc-issue-reports/issues/308 
https://github.com/scipy/scipy/issues/5240

From ilayn in the second link:
"Seems like you have two scipy installations interfering with each other. The solution is actually "That shouldn't happened". Make sure that you don't have multiple installations."

Hope it helps.

Regards,
yl
