### ISSUE TITLE
Can you share your DMPNet Code?

### ISSUE THREAD

**Issue by ZhuLingfeng1993** [Yuliang-Liu/Curve-Text-Detector#20]

**Comment by Yuliang-Liu** [comment]
Hi there, 
We will only consider sharing a updated version of DMPNet, which might be after the paper had been published (we hope you could understand). 
If you need, we can provide you with the module of original implement, e.g., gpu version of MenteCarlo pnms. 

Regards,
yl

**Comment by Yuliang-Liu** [comment]
Yes. I will let you know if it is published.

I have sent you the email. For more details about DMPNet, we can discuss via email. 

Because this issue is not relevent about this repository, it would be closed.

Best Regards

**Comment by bobyguo** [comment]
@Yuliang-Liu Would you please share the code of DMPNet?

**Comment by Yuliang-Liu** [comment]
@bobyguo Yes, I can share the code once I have a little free time to do so. But would you mind tell me what the purpose is? Because I thought it is a little bit outdated.

**Comment by Yuliang-Liu** [comment]
@doudoubilly Sent.

The implement parallels the number of bounding boxes, which is much faster than paralling the sampling points. Simultaneously paralleing both two terms requires cuda dynamic parallel, but it can only imporve the speed slightly.
