### ISSUE TITLE
请问列出的对比表格（跟textsnake对比）中，其他算法用的训练数据和你的算法相同吗？

### ISSUE THREAD

**Issue by wenston2006** [Yuliang-Liu/Curve-Text-Detector#22]

**Comment by Yuliang-Liu** [comment]
其他的文章链接已经给出，您可以直接看原文的。引用Textsnake里面的 “Experiments on Curved Text (Total-Text and CTW1500) Fine-tuning on these two datasets stops at about 5k iterations.”
