### ISSUE TITLE
ctw1500 object has no attribute 'set_proposal_method'

### ISSUE THREAD

**Issue by ran337287** [Yuliang-Liu/Curve-Text-Detector#24]
I ran ./tools/test_net.py and got the error ctw1500 object has no attribute 'set_proposal_method'.
And I uncommented set_proposal_method in imdb.py, then got another error ctw1500 object has no attribute 'selective_search_roidb'.

So why comment these code?  Is there code can be executed directly?

**Comment by Yuliang-Liu** [comment]
We have tested the code on various machines, and it can be executed directly following the instruction. I will try to reproduce your issue and figure out why this happened.

**Comment by zhangshuaitao** [comment]
@ran337287 , your problem should be caused by setting has_rpn in experiments/cfgs/rfcn_ctd.yml  to false.  If so, the code will use the selective_search_roidb instead of RPN  to generate proposals. You can solve this problem by changing it to ture.
