### ISSUE TITLE
框图工具输入文本后怎么保存啊

### ISSUE THREAD

**Issue by zhuliqian** [Yuliang-Liu/Curve-Text-Detector#26]
![image](https://user-images.githubusercontent.com/17901084/50411270-ac657880-0839-11e9-9332-ed97693fbed8.png)
这样之后点了叉号并没有显示
![image](https://user-images.githubusercontent.com/17901084/50411288-d454dc00-0839-11e9-9daf-93af3bd1c218.png)

**Comment by zhangshuaitao** [comment]
您好，在输入完毕之后只需要按一下Enter键即可。 @zhuliqian

**Comment by zhuliqian** [comment]
谢谢 @zhangshuaitao
