### ISSUE TITLE
use your own Makefile.config to compile?

### ISSUE THREAD

**Issue by xieyufei1993** [Yuliang-Liu/Curve-Text-Detector#27]
what does this mean?
cd ROOT/caffe/ and use your own Makefile.config to compile 

@Yuliang-Liu

**Comment by xieyufei1993** [comment]
Thanks for your reply, I also want to know how to train my own data, the format is just like this :x1,y1,x2,y2,x3,y3,x4,y4,text, look forward to hearing from you !
@zhangshuaitao

**Comment by zhangshuaitao** [comment]
the format is just like this :xmin,ymin, xmax, ymax,p1_w, p1_h, p2_w, p2_h, ..., pi_w, pi_h, ..., p14_w, p14_h. The total number of the gt items is 32; The first four values are the x,y minimum and maximum of the
circumscribed rectangle. the remaining 28 values are the offset of the 14 points. 
file:///home/zst/Desktop/ctw_shuju.png

**Comment by zhangshuaitao** [comment]
The format is just like this : xmin, ymin, xmax, ymax, pw_1, ph_1, pw_2, ph_2, ..., pw_14, ph_14. The total number is of gt items is 32. The first 4 values are x, y minimum and maximum of the circumscribed rectangle. The remaining 28 values are the offsets of the 14 points.  You can refer to the figure below.
![_20190123184426](https://user-images.githubusercontent.com/30206688/51601310-f7f56a00-1f3e-11e9-8b18-badd83bcfccb.jpg)
@xieyufei1993

**Comment by xieyufei1993** [comment]
ok，thank you very much!

**Comment by Yuliang-Liu** [comment]
@xieyufei1993 Given a GT annotation, using x_i = x_min+ pw_i and y_i = y_min + ph_i to get coordinates of all 14 points.
