### ISSUE TITLE
How to generate offsets for a dataset?

### ISSUE THREAD

**Issue by sherif7810** [Yuliang-Liu/Curve-Text-Detector#29]
I want to use TotalText with the model. I get list out of index at the line `gt_info[ix,:] = [float(items[i].strip()) for i in range(4,32)] # syn`.

Rectangle ground-truth has x & y minimum & maximum.
Polygon ground-truth has variable length.

**Comment by zhangshuaitao** [comment]
@sherif7810  if you want to use TotalText with our model，you have to change the ground-truth to be the same as CTW1500.  You can refer to > https://github.com/Yuliang-Liu/Curve-Text-Detector/issues/27#issuecomment-456755956.  Wish you all the best.
