### ISSUE TITLE
CPU mode error

### ISSUE THREAD

**Issue by WLswert** [Yuliang-Liu/Curve-Text-Detector#3]
Hi ！
when  i  run the test.sh in cpu mode , 
i got the error:  psroi_pooling_layer.cpp:56] Not Implemented Yet !
I found there is only GPU mode  files ,and the cpu mode ( psroi_pooling_layer.cpp ) file is  not  complete.
can you Implemente the code ?  thx!

**Comment by Yuliang-Liu** [comment]
Hi,

Actually, the gpu mode psroi_pooling is not written by me. It's written by the authors of R-FCN, so maybe you can ask them for official cpu implement.

**Comment by bygreencn** [comment]
@WLswert you can follow #6
