### ISSUE TITLE
“caffe.LayerParameter”has no field named "psroi_pooling_param"

### ISSUE THREAD

**Issue by BigPandaCPU** [Yuliang-Liu/Curve-Text-Detector#30]
Hi,Liu
While I run demo.py in my window-caffe in cpu model, it gives errors “caffe.LayerParameter”has no field named "psroi_pooling_param",I googled this issue ,but failed to get useful information, could you please give me some advice?

**Comment by zhangshuaitao** [comment]
@BigPandaCPU  Hi，
 Actually,  the cpu mode psroi_pooling layer is not executed by us.  It's written by the authors of R-FCN, so maybe you can ask them for official cpu implement. You can refer to [https://github.com/Yuliang-Liu/Curve-Text-Detector/issues/6#issue-285642401](url).  Wish you all the best.
