### ISSUE TITLE
识别部分标签的链接

### ISSUE THREAD

**Issue by lxx1884896** [Yuliang-Liu/Curve-Text-Detector#35]
您好，请问能提供一下数据集识别标签的百度云网盘链接吗，我这边onedrive的链接打不开

**Comment by Yuliang-Liu** [comment]
Hi there，

Baidu Yun Link:
Link：https://pan.baidu.com/s/1y_bvXTAsJibsxDxkl2PlPA 
Pwd：brwm 

See if it helps. Feel free to let me know if you enconter further problems.

Regards,
yl
