### ISSUE TITLE
Convert annotations of other datasets to CTW's format

### ISSUE THREAD

**Issue by doudoubilly** [Yuliang-Liu/Curve-Text-Detector#36]
Hello!

The annotations in the CTW1500 retain the text reading order, which is very percious in data annotation. And the results on the CTW1500 can be reproduced very successfully.

I also try to reproduce the results of CTD+TLOC on Total-Text and MSRA-TD500. Then I need to convert these two data sets into CTW's annotation format, which means that their reading order also needs to be retained.

How can I complete such a conversion? In the original paper for Total-Text 
"**Because the annotated numbers for this dataset are not fixed and the point positions are subjectively determined, we extracted the text boundaries and used a similar LSI method to resample the annotated points.**"

Could you give more details on the conversion process?

**Comment by Dive-frank** [comment]
Hi:
I have one solution,maybe will help.
For example: a box of text image of total text ,you can use cv2.fillpoly to draw box in a blank image shaped as the original image.And then you can use cv2.findContous to find the coordinate of boundary。Fourteen points can be selected from a set of coordinates at equal-phase interval
. Finally you will  finish the convert. 

Best.

**Comment by doudoubilly** [comment]
@Dive-frank 
Hi,
That's quite a nice suggestion. I will try it soon.
Thanks a lot.

**Comment by Yuliang-Liu** [comment]
@Dive-frank  That's exactly what we did, thanks!

**Comment by wawaa** [comment]
> 

@Dive-frank 
Hi:
Do you have any idea abou how to get the 'equal-phase interval'? Thx!

**Comment by wawaa** [comment]
> Hi: I have one solution,maybe will help. For example: a box of text image of total text ,you can use cv2.fillpoly to draw box in a blank image shaped as the original image.And then you can use cv2.findContous to find the coordinate of boundary。Fourteen points can be selected from a set of coordinates at equal-phase interval . Finally you will finish the convert.
> 
> Best.

@Dive-frank 
Hi:
Thanks for your reply. Do you have any idea abou how to get the 'equal-phase interval'? Thx!
