### ISSUE TITLE
About the annotation 14points

### ISSUE THREAD

**Issue by yyjabiding** [Yuliang-Liu/Curve-Text-Detector#38]
It seems that the 14points generated do not follow the clockwise or anti-clockwise order before  
feeding into the function cv2.drawcontours in ctw1500_loader.py?
could you explain why?
Thanks a lot.

**Comment by zhangshuaitao** [comment]
@yyjabiding ,the 14points generated follow the order of text reading。

**Comment by zhangshuaitao** [comment]
> sorry I am still confused about what the order of text reading is.

HI，just like this "Text":
![456](https://user-images.githubusercontent.com/30206688/60228549-93f81880-98c5-11e9-9877-8cfdede7fc67.png)

**Comment by yyjabiding** [comment]
thanks for your explanation.
