### ISSUE TITLE
how to decide the x , y minimum and maximum of the circumscribed rectangel  in the lable text?

### ISSUE THREAD

**Issue by 10183308** [Yuliang-Liu/Curve-Text-Detector#4]
Hi ,
Thank you for your contribution of the paper.

I have a question about the label text file.

how to decide the x , y minimum and maximum of the circumscribed rectangel  in the lable text?

Could give me some advise?

thank you very much.

**Comment by Yuliang-Liu** [comment]
Hi,
Thanks

You can refer the README file inside the data/. The first four values each line are x , y minimum and maximum of the circumscribed rectangle.

You are welcome.
