### ISSUE TITLE
关于评测的问题

### ISSUE THREAD

**Issue by Banyueqin** [Yuliang-Liu/Curve-Text-Detector#40]
您好：
是txt结果每个box坐标必须在一行吗，比如我的一个box坐标是好几行坐标

**Comment by Banyueqin** [comment]
Curve-Text-Detector/tools/ctw1500_evaluation/voc_eval_polygon.py", line 137, in voc_eval_polygon
    BB = np.array([[float(z) for z in x[2:]] for x in splitlines])
ValueError: could not convert string to float:

**Comment by Banyueqin** [comment]
会出这个错误

**Comment by Yuliang-Liu** [comment]
在一行，格式可以参考给出的例子

**Comment by Yuliang-Liu** [comment]
评测也可以参考 https://github.com/Yuliang-Liu/TIoU-metric/tree/master/curved-tiou  也有给出样例，可能更容易一点评估，供你参考~
