### ISSUE TITLE
inconsistency of gt labels from CTW-1500-reg-label.zip and ctw1500.zip

### ISSUE THREAD

**Issue by PkuDavidGuan** [Yuliang-Liu/Curve-Text-Detector#41]
There are some inconsistency of gt labels from CTW-1500-reg-label.zip and ctw1500.zip. For example, in 1017.txt, there are 21 instances in CTW-1500-reg-label.zip and 20 instances in ctw1500.zip.

**Comment by PkuDavidGuan** [comment]
Also some mislabellings in CTW-1500-reg-label.zip. For example, some "'" are annotated as the chinese "‘", some "," are annotated as the chinese "，".

**Comment by Yuliang-Liu** [comment]
Thanks for pointing out the issue. We will thoroughly correct the recognition annotation once we have time. It would be much appreciated if you can provide the image id you have found that is incorrect or inconsistency.

**Comment by PkuDavidGuan** [comment]
Sorry, I didn't note down all the incorrect images, and I remember 1017 have some mislabellings. Besides, I hope the future revised version can fix the following issues: 1) the order of text instances in the  CTW-1500-reg-label.zip and ctw1500.zip may be different. 2) the number of text instances in the  CTW-1500-reg-label.zip and ctw1500.zip may be different. 3) Now the  separator in each line of annotations in CTW-1500-reg-label.zip is ',', but ',' may exist in the recognition labels. For example, the line a = "px1, py1, px2, py2,...,px14,py14,"xx, xx"" will be split into  [px1, py1,...,'"xx,', 'xx'] by a.split(','). I think the recognition label should be in a seperate line.

**Comment by Yuliang-Liu** [comment]
Thanks for your constructive  suggestions. For 3), I don’t think it is a problem as the number of coordinates are fixed.

**Comment by PkuDavidGuan** [comment]
Hi, Yuliang:

   I have another problem now. I found the detection labelling (in the directory 'test/text_label_circum' in ctw1500.zip), the recognition labelling (CTW-1500-reg-label.zip) and the evaluation labelling in https://github.com/Yuliang-Liu/TIoU-metric/tree/master/curved-tiou/ctw1500-gt.zip have different coordinates. 
   It seems that the phenomenon appears in every annotation, and I don't know which one is used for the final evaluation.

**Comment by Yuliang-Liu** [comment]
Hi Yushuo,

Thanks again. I will temporally close the link for recognition label file. Please do not use CTW-1500-reg-label.zip at this moment. I will let you know once the updating is done.

**Comment by zhangshuaitao** [comment]
Hi Yushuo,
We has updated thre recognition label file. Thank you for your attention.

**Comment by PkuDavidGuan** [comment]
Thanks for that~
