### ISSUE TITLE
About the annotation

### ISSUE THREAD

**Issue by SakuraRiven** [Yuliang-Liu/Curve-Text-Detector#43]
Hi, thank you for releasing the dataset. I have a question about the annotation. 

Generally, each polygon(include quadrangle box) has 14 points, which follow the order of text reading. Are those points sampled uniformly？In other words, can we consider that the 1st, 7th, 8th and 14th points are exactly the vertices?

**Comment by Yuliang-Liu** [comment]
Yes, they are.

**Comment by SakuraRiven** [comment]
Thank you!
