### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by mugeshuzi** [Yuliang-Liu/Curve-Text-Detector#45]
The dataset url is invalid now,can you upgrade it or show me where I can download it. Thanks very much for your attention.

**Comment by zhangshuaitao** [comment]
@mugeshuzi ，Can you let me know which link you are referring to ?

**Comment by jstacer1** [comment]
> @mugeshuzi ，Can you let me know which link you are referring to ?

wget -O test_labels.zip https://cloudstor.aarnet.edu.au/plus/s/uoeFl0pCN9BOCN5/download
