### ISSUE TITLE
Annotating labels! Word-2-Word only?

### ISSUE THREAD

**Issue by innat** [Yuliang-Liu/Curve-Text-Detector#52]
@Yuliang-Liu 
I'm doing annotation using these tools. However, I'm sorry, I didn't check the manual until you've mentioned. It's great. Thank you.

However, I have a very basic question on annotation. While annotating, should we annotate word by word or should we annotate phrase-wise, or is something that depends on our end goal? To make my query cleaner, here is an example:

let's say, there's a sentence: **Made In Australia**, now while annotating, we can do:

1. `Made` `In` `Australia`
2. `Made In Australia`

In case 1. we label `word-wise` but in case 2. we label `context-wise`, right? So, which one is more appropriate? My understanding, our visual prediction will be the same as we label them. So, if I choose case 1., my prediction would be like that and if I choose case 2. my prediction would be like that. ....... 

Or, we should go with case 1. approach and case 2. is simply just a post-processing method? Is there anything a post-processing method? 

Or, I'm just over-thinking. It mainly depends on our end goal. If we want to recognize word-wise, we should go with case 1. but if our end goal is something like case 2. then we should label the text in context-wise.

I hope you get my point. Thank you. :)

**Comment by Yuliang-Liu** [comment]
@innat Good to see you again,

It depends on your end goal. Word-level may cause less confusion, while text-line-level may be much intuitive and easy to annotate.

Specifically, to the best of our knowledge, there is not any objective conclusion showing whether word-level annotation or text-line-level annotation is better for a detector. Although word-level can reduce the degree of curvature, it requires many exquisite detections to separate the words. For example, as shown in below figure, word-level annotation requires smaller and more accurate detections to localize the words, even if the intervals may not be obvious, whereas line-level detection only requires single detection, which is much easier for detection in practice.
![image](https://user-images.githubusercontent.com/34134635/85483718-8b374100-b604-11ea-9dcf-7db64cbe82a3.png)


Hope I address your concerns correctly.

**Comment by innat** [comment]
@Yuliang-Liu san, Thank you. It simplifies my concern. 💯
