### ISSUE TITLE
how to use Labeling tool to label curved text?

### ISSUE THREAD

**Issue by samantha0-ops** [Yuliang-Liu/Curve-Text-Detector#54]
I am labeling my own dataset with the Labeling tool you provided, but I don't know the exact steps when labeling curved text. 
Maybe the guiding gif is too quick and I missed some key points? 
Waiting for more accurate guidance.

**Comment by Yuliang-Liu** [comment]
There is a manual book. I am sure you can find it.

**Comment by samantha0-ops** [comment]
> There is a manual book. I am sure you can find it.

Thank you so much!

**Comment by AchoWu** [comment]
Hello, could you tell me where to find the manual book, I have the same question. Is it in windows_label_tool?
