### ISSUE TITLE
Does it work on windows?

### ISSUE THREAD

**Issue by bygreencn** [Yuliang-Liu/Curve-Text-Detector#6]
Hi Sir:
I had compiled it on windows 7 with and without CUDA 8.0(cudnn 5.1 and cudnn 6 .0), but when run test_net.py, it could not get correct porposal, all scores of proposal is 0.5?
And also test on Linux,  it is ok with GPU, but with CPU, the scores of proposal is correct and same with GPU when read bottom from cpu_data, but the final result is not detecting the text?
So, what make it only work on Linux, how to port to Windows? what is the keypoint?
Thank you very much!
@yl9393 @Yuliang-Liu 
BR
bygreencn

**Comment by bygreencn** [comment]
With [CaiYang's pull requests  ](https://github.com/daijifeng001/caffe-rfcn/pull/10), CPU mode working. But still could not work on windows.

**Comment by bygreencn** [comment]
Carefully merge with caffe‘s windows branch， it is ok.

**Comment by xrf116** [comment]
@bygreencn Can you share your windows project?
