### ISSUE TITLE
any other way to share the models and dataset?

### ISSUE THREAD

**Issue by rachelmint** [Yuliang-Liu/Curve-Text-Detector#7]
I have no way to download data from baidu pan.

**Comment by yl9393** [comment]
Hi,
try these (OneDrive):
https://1drv.ms/u/s!Aplwt7jiPGKilH0rLDFrRof8qmRD  ctd_tloc.caffemodel
https://1drv.ms/u/s!Aplwt7jiPGKilH4XzZPoKrO7Aulk   ctw1500.zip
https://1drv.ms/u/s!Aplwt7jiPGKilHwMsW2N_bfnb0Bx    ResNet-50-model.caffemodel

Hope these would be helpful.

**Comment by rachelmint** [comment]
it works! thanks a lot yl9393

**Comment by junhocho** [comment]
Hi, as foreigner, cannot access to baidu cloud.
Want to access following:

The visualization of the annotated images can be downloaded through the following link:
(https://pan.baidu.com/s/1eR641zG PASSWORD: 5xei) (BaiduYun. Size = 696 Mb).

Can you upload in on ondedrive too?

**Comment by Yuliang-Liu** [comment]
Hi there,

Sure. Here is the onedrive link: https://1drv.ms/u/s!AradqGvJ8EbtbiPjNwDgzjms0Vg 

Regards,
yl
