### ISSUE TITLE
When the labeling tool will be released ?

### ISSUE THREAD

**Issue by rmmal** [Yuliang-Liu/Curve-Text-Detector#8]
When the labeling tool will be released ?

**Comment by Yuliang-Liu** [comment]
Hi, currently the instruction is based on Chinese scripts. I'm trying to transfer it into English version and make it better.

Now, Chinese tomb-sweeping festival is coming, which may take me two days for ancestor worship. So I guess I would finish the tool within a week. I will release the tools on Windows, Ubuntu 14.04 and 16.04 systems. 

Sorry for the delay.

Yuliang Liu

**Comment by rmmal** [comment]
Thanks Yuliang :+1:

**Comment by Yuliang-Liu** [comment]
The labeling tool has been released. If there is any problem, please let me know.

Hope it helps.

Regards,
Yuliang Liu
