### ISSUE TITLE
 Failed to parse NetParameter file: ../models/ctd/test_ctd_tloc.prototxt

### ISSUE THREAD

**Issue by earthat** [Yuliang-Liu/Curve-Text-Detector#9]
HI

I am working on ubutu17.10 and installed caffe prebuilt bainaries for ubuntu>17.04. Everything was setup and when I run the demo.py in tools, I get this error

`WARNING: Logging before InitGoogleLogging() is written to STDERR
W0406 18:33:40.810593  4823 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0406 18:33:40.810638  4823 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0406 18:33:40.810642  4823 _caffe.cpp:142] Net('../models/ctd/test_ctd_tloc.prototxt', 1, weights='../output/ctd_tloc.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 3767:25: Message type "caffe.LayerParameter" has no field named "psroi_pooling_param".
F0406 18:33:40.812146  4823 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ../models/ctd/test_ctd_tloc.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
`

Please help me to resolve the issue.

With Regards

**Comment by Yuliang-Liu** [comment]
I haven't test my code on ubuntu17.10 (only tested on 14.04 and 16.04), and my code is based on a relative old caffe version with some old libraries (e.g., requiring protobuf 2). I'm not sure whether it can be run on a new caffe version.

The log showed "Message type "caffe.LayerParameter" has no field named "psroi_pooling_param"", which I guess is the main issue. I suggest you checking how psroipooling layer is defined and registered. Make sure it is included in caffe.proto file. 

Regards,
Yuliang Liu

**Comment by earthat** [comment]
yes, the parsing issue of this prototxt file is there. I tried by replacing the network in this file with googlenet and it was parsed. So I suppose it is included in caffe.proto file. How do you use or define the fastrcnn network. Is there any source form where you take it or idealize it as several fast-rcnn for caffe are available and I get just confused.

**Comment by earthat** [comment]
I don;t know exactly but I found that when this part of that prototxt file is removed then the error of psroi_pooling_param goes but another issue of cuda out of memory popup.

part of test_ctd_tloc_prototxt which causes issue

`#========= RoI Proposal ============

layer {
  name: "rpn_cls_prob"
  type: "Softmax"
  bottom: "rpn_cls_score_reshape"
  top: "rpn_cls_prob"
}

layer {
  name: 'rpn_cls_prob_reshape'
  type: 'Reshape'
  bottom: 'rpn_cls_prob'
  top: 'rpn_cls_prob_reshape'
  reshape_param { shape { dim: 0 dim: 24 dim: -1 dim: 0 } }
}

layer {
  name: 'proposal'
  type: 'Python'
  bottom: 'rpn_cls_prob_reshape'
  bottom: 'rpn_bbox_pred'
  bottom: 'im_info'
  top: 'rois'
#  top: 'rpn_scores'
  python_param {
    module: 'rpn.proposal_layer'
    layer: 'ProposalLayer'
    param_str: "'feat_stride': 16"
  }
}

#----------------------new conv layer------------------
layer {
    bottom: "res5b"
    top: "conv_new_1"
    name: "conv_new_1"
    type: "Convolution"
    convolution_param {
        num_output: 1024
        kernel_size: 1
        pad: 0
        weight_filler {
            type: "gaussian"
            std: 0.01
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
    param {
        lr_mult: 1.0
    }
    param {
        lr_mult: 2.0
    }
}

layer {
    bottom: "conv_new_1"
    top: "conv_new_1"
    name: "conv_new_1_relu"
    type: "ReLU"
}

layer {
    bottom: "conv_new_1"
    top: "rfcn_cls"
    name: "rfcn_cls"
    type: "Convolution"
    convolution_param {
        num_output: 98 # 2*(7^2) cls_num*(score_maps_size^2)
        kernel_size: 1
        pad: 0
        weight_filler {
            type: "gaussian"
            std: 0.01
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
    param {
        lr_mult: 1.0
    }
    param {
        lr_mult: 2.0
    }
}
layer {
    bottom: "conv_new_1"
    top: "rfcn_bbox"
    name: "rfcn_bbox"
    type: "Convolution"
    convolution_param {
        num_output: 392 # 2*4*(7^2) cls_num*cors*(score_maps_size^2)
        kernel_size: 1
        pad: 0
        weight_filler {
            type: "gaussian"
            std: 0.01
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
    param {
        lr_mult: 1.0
    }
    param {
        lr_mult: 2.0
    }
}
# curve
layer {
    bottom: "conv_new_1"
    top: "rfcn_bbox_info_h"
    name: "rfcn_bbox_info_h"
    type: "Convolution"
    convolution_param {
        num_output: 784
        kernel_size: 1
        pad: 0
        weight_filler {
            type: "gaussian"
            std: 0.01
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
    param {
        lr_mult: 1.0
    }
    param {
        lr_mult: 2.0
    }
}
layer {
    bottom: "conv_new_1"
    top: "rfcn_bbox_info_w"
    name: "rfcn_bbox_info_w"
    type: "Convolution"
    convolution_param {
        num_output: 784
        kernel_size: 1
        pad: 0
        weight_filler {
            type: "gaussian"
            std: 0.01
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
    param {
        lr_mult: 1.0
    }
    param {
        lr_mult: 2.0
    }
}

#--------------position sensitive RoI pooling--------------
layer {
    bottom: "rfcn_cls"
    bottom: "rois"
    top: "psroipooled_cls_rois"
    name: "psroipooled_cls_rois"
    type: "PSROIPooling"
    psroi_pooling_param {
        spatial_scale: 0.0625
        output_dim: 2
        group_size: 7
    }
}

layer {
    bottom: "psroipooled_cls_rois"
    top: "cls_score"
    name: "ave_cls_score_rois"
    type: "Pooling"
    pooling_param {
        pool: AVE
        kernel_size: 7
        stride: 7
    }
}


layer {
    bottom: "rfcn_bbox"
    bottom: "rois"
    top: "psroipooled_loc_rois"
    name: "psroipooled_loc_rois"
    type: "PSROIPooling"
    psroi_pooling_param {
        spatial_scale: 0.0625
        output_dim: 8  # 2*4 cls * cor_nums
        group_size: 7  # 7**2
    }
}

layer {
    bottom: "psroipooled_loc_rois"
    top: "bbox_pred_pre"
    name: "ave_bbox_pred_rois"
    type: "Pooling"
    pooling_param {
        pool: AVE
        kernel_size: 7
        stride: 7
    }
}

#--------------curve position sensitive RoI pooling--------------
layer {
    bottom: "rfcn_bbox_info_h"
    bottom: "rois" # rois_fg
    top: "psroipooled_loc_rois_info_h"
    name: "psroipooled_loc_rois_info_h"
    type: "PSROIPooling"
    psroi_pooling_param {
        spatial_scale: 0.0625
        output_dim: 16
        group_size: 7
    }
}

################lstm#######################
# prepare lstm inputs
layer {
  name: "lstm_input_reshape_h"
  type: "Reshape"
  bottom: "psroipooled_loc_rois_info_h"
  top: "im2col_transpose_h"
  reshape_param {
    shape { dim: 0 dim: -1 dim: 1 dim: 16}
    # axis: 1
    # num_axes: 1
  }
}

layer {
  name: "conv_lstm_h"
  type: "Convert"
  bottom: "im2col_transpose_h"
  top: "conv_lstm_h"
  top: "cont_sentence_h"
}

layer {
    name: "lstm1_h"
    type: "LSTM"
    bottom: "conv_lstm_h"
    bottom: "cont_sentence_h"
    top: "lstm1_h"
    recurrent_param {
        num_output: 128
        weight_filler {
            type: "xavier"
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
}
# ============ reverse lstm =============
layer {
  name: "lstm1-reverse1"
  type: "Reverse"
  bottom: "lstm1_h"
  top: "rlstm1_input"
  reverse_param {
    axis: 0
  }
}
layer {
  name: "lstm1-reverse1-cont"
  type: "Reverse"
  bottom: "cont_sentence_h"
  top: "rlstm1_cont_sentence_h"
  reverse_param {
    axis: 0
  }
}
layer {
    name: "lstm2_h"
    type: "LSTM"
    bottom: "rlstm1_input"
    bottom: "rlstm1_cont_sentence_h"
    top: "rlstm2_h"
    recurrent_param {
        num_output: 128
        weight_filler {
            type: "xavier"
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
}
layer {
  name: "lstm1-reverse2"
  type: "Reverse"
  bottom: "rlstm2_h"
  top: "lstm2_h"
  reverse_param {
    axis: 0
  }
}
# merge lstm1 and rlstm1
layer {
  name: "blstm1"
  type: "Concat"
  bottom: "lstm1_h"
  bottom: "lstm2_h"
  top: "blstm1"
  concat_param {
    axis: 2
  }
}

layer {
  name: "lstm_output_reshape_h"
  type: "Reshape"
  bottom: "blstm1"
  top: "lstm_output_reshape_h"
  reshape_param {
    shape { dim: -1 dim: 1 }
    axis: 1
    num_axes: 1
  }
}
layer {
  name: "im2col_transpose2_h"
  bottom: "lstm_output_reshape_h"
  top: "im2col_transpose2_h"
  type: "Transpose"
  transpose_param {
    dim: 1
    dim: 0
    dim: 2
    dim: 3
  }
}

layer {
    bottom: "im2col_transpose2_h"
    top: "info_syn_pred_h"
    name: "ave_bbox_pred_rois_info_curve_h"
    type: "Pooling"
    pooling_param {
        pool: AVE
        kernel_w: 256
        kernel_h: 1
        stride_w: 256
        stride_h: 1
    }
}

###################### w lstm
layer {
    bottom: "rfcn_bbox_info_w"
    bottom: "rois" # rois rois_fg
    top: "psroipooled_loc_rois_info_w"
    name: "psroipooled_loc_rois_info_w"
    type: "PSROIPooling"
    psroi_pooling_param {
        spatial_scale: 0.0625
        output_dim: 16
        group_size: 7
    }
}

################lstm#######################
# prepare lstm inputs
layer {
  name: "lstm_input_reshape_w"
  type: "Reshape"
  bottom: "psroipooled_loc_rois_info_w"
  top: "im2col_transpose_w"
  reshape_param {
    shape { dim: 0 dim: -1 dim: 1 dim: 16}
    # axis: 1
    # num_axes: 1
  }
}

layer {
  name: "conv_lstm_w"
  type: "Convert"
  bottom: "im2col_transpose_w"
  top: "conv_lstm_w"
  top: "cont_sentence_w"
}

layer {
    name: "lstm1_w"
    type: "LSTM"
    bottom: "conv_lstm_w"
    bottom: "cont_sentence_w"
    top: "lstm1_w"
    recurrent_param {
        num_output: 128
        weight_filler {
            type: "xavier"
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
}
# ============ reverse lstm =============
layer {
  name: "lstm1-reverse1-w"
  type: "Reverse"
  bottom: "lstm1_w"
  top: "rlstm1_input_w"
  reverse_param {
    axis: 0
  }
}
layer {
  name: "lstm1-reverse1-cont-w"
  type: "Reverse"
  bottom: "cont_sentence_w"
  top: "rlstm1_cont_sentence_w"
  reverse_param {
    axis: 0
  }
}
layer {
    name: "lstm2_w"
    type: "LSTM"
    bottom: "rlstm1_input_w"
    bottom: "rlstm1_cont_sentence_w"
    top: "rlstm2_w"
    recurrent_param {
        num_output: 128
        weight_filler {
            type: "xavier"
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
}
layer {
  name: "lstm1-reverse2-w"
  type: "Reverse"
  bottom: "rlstm2_w"
  top: "lstm2_w"
  reverse_param {
    axis: 0
  }
}
# merge lstm1 and rlstm1
layer {
  name: "blstm1-w"
  type: "Concat"
  bottom: "lstm1_w"
  bottom: "lstm2_w"
  top: "blstm1_w"
  concat_param {
    axis: 2
  }
}

# =======================================
layer {
  name: "lstm_output_reshape_w"
  type: "Reshape"
  bottom: "blstm1_w"
  top: "lstm_output_reshape_w"
  reshape_param {
    shape { dim: -1 dim: 1 }
    axis: 1
    num_axes: 1
  }
}
layer {
  name: "im2col_transpose2_w"
  bottom: "lstm_output_reshape_w"
  top: "im2col_transpose2_w"
  type: "Transpose"
  transpose_param {
    dim: 1
    dim: 0
    dim: 2
    dim: 3
  }
}

layer {
    bottom: "im2col_transpose2_w"
    top: "info_syn_pred_w"
    name: "ave_bbox_pred_rois_info_curve_w"
    type: "Pooling"
    pooling_param {
        pool: AVE
        kernel_w: 256
        kernel_h: 1
        stride_w: 256
        stride_h: 1
    }
}

#--------------CURVE position sensitive RoI pooling--------------
layer {
   name: "cls_prob"
   type: "Softmax"
   bottom: "cls_score"
   top: "cls_prob_pre"
}

layer {
    name: "cls_prob_reshape"
    type: "Reshape"
    bottom: "cls_prob_pre"
    top: "cls_prob"
    reshape_param {
        shape {
            dim: -1
            dim: 2
        }
    }
}

layer {
    name: "bbox_pred_reshape"
    type: "Reshape"
    bottom: "bbox_pred_pre"
    top: "bbox_pred"
    reshape_param {
        shape {
            dim: -1
            dim: 8
        }
    }
}

layer {
    name: "info_pred_reshape_h"
    type: "Reshape"
    bottom: "info_syn_pred_h"
    top: "info_pred_h"
    reshape_param {
        shape {
            dim: -1
            dim: 16
        }
    }
}

layer {
    name: "info_pred_reshape_w"
    type: "Reshape"
    bottom: "info_syn_pred_w"
    top: "info_pred_w"
    reshape_param {
        shape {
            dim: -1
            dim: 16
        }
    }
}`
